

[tool.epab]
# Package name
# value type: string
# MANDATORY CONFIG VALUE
package_name = "epab"

# Less console output
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
# quiet = 

# More console output
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
verbose = true


[tool.epab.appveyor]
# List of artifacts for Appveyor
# value type: List of strings
# This configuration is optional and comes with a default setting
# default: []
# artifacts = 

# Additional command line options for tests run on AV
# value type: string
# This configuration is optional and comes with a default setting
# default: --long
# test_runner_options = 


[tool.epab.changelog]
# Disable changelog building
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
# disable = 

# Path to changelog file
# value type: path
# This configuration is optional and comes with a default setting
# default: CHANGELOG.rst
# file_path = 


[tool.epab.doc]
# Local documentation directory
# value type: path
# This configuration is optional and comes with a default setting
# default: ./doc
# folder = 

# Documentation repository on Github
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# repo = 


[tool.epab.freeze]
# PyInstaller data-files list
# value type: List of strings
# This configuration is optional and comes with a default setting
# default: []
# data_files = 

# Main entry point for pyinstaller
# value type: string
# This configuration is optional and comes with a default setting
# default: None
# entry_point = 


[tool.epab.lint]
# List of comma separated files for flake8 to exclude
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# flake8_exclude = 

# Linter max line width
# value type: integer
# This configuration is optional and comes with a default setting
# default: 120
# line_length = 

# Additional MyPy arguments
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# mypy_args = 


[tool.epab.qt]
# Qt resource file (.qrc) location
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# res_src = 

# Compiled Qt resource file (.py) target location
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# res_tgt = 


[tool.epab.test]
# Minimal coverage to pass tests
# value type: integer
# This configuration is optional and comes with a default setting
# default: 20
# coverage_fail_under = 

# Amount of \slow\ tests to show
# value type: integer
# This configuration is optional and comes with a default setting
# default: 10
# duration_count = 

# Additional options for test run
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# runner_options = 

# Target of pytest
# value type: string
# This configuration is optional and comes with a default setting
# default: test
# target = 
